### ISSUE TITLE
regarding ouput of the prediction

### ISSUE THREAD

**Issue by anis016** [gaterslebenchen/JLibFM#1]
hello,

I ran the Main.java for sgd and got the output as below.

4.5108266777588675
4.351852985294726
4.436254884330109
4.262971429260305
3.9958538220015614
4.339484357661571
3.850038392953512
3.7985576085510266
3.8784619927484814
3.267392136769114
3.6320045321027394
3.702190038454649
4.345670636562737
.
.

is there anyway to know, for which user and item the predicted rating is ?

Thanks

**Comment by gaterslebenchen** [comment]
I added two files: com.github.gaterslebenchen.libfm.examples.MovieLens1MFormaterWithMetaData and 
com.github.gaterslebenchen.libfm.examples.SplitDataWithMetaData, you could generate your train dataset, valid dataset and test dataset with these two files, the "SplitDataWithMetaData" class will create a "ratings_test.libfm.meta" file in your current folder, the content of "ratings_test.libfm.meta" is:
userid + whitespace + moveid + whitespace + index.
You could load "ratings_test.libfm.meta" into a HashMap, the key is "index", the value is "userid + whitespace + moveid", then in the function "save(double[] value, String filename)" of "com.github.gaterslebenchen.libfm.tools.Util" class, change the "outfile.write(Double.toString(value[i]));" to
"outfile.write(yourhashmap.get(i) + " " +Double.toString(value[i]));".

**Comment by anis016** [comment]
Perfect ! It worked ... thank you soo much :-)  :+1:
